project:
  type: website
  output-dir: ../docs
  preview:
    port: 8000


website:
  title: "| Reference Datasets"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: datasets.qmd
        text: Datasets
      - href: https://crafd.io/our-work
        text: Who We Are
    tools:
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/UN-CRAFd/crafd-reference-datasets
          - text: Report a Bug
            href: https://github.com/UN-CRAFd/crafd-reference-datasets/issues/new
        

format:
  html:
    # brand: _brand.yml
    theme:
      - brand
      - styles.scss
    toc: true
    toc-location: left
    css: styles.css
    
