---
title: "Available Datasets"
format: html
---


```{r setup}
#| include: false
library(tidyverse)

GITHUB_BASE_URL <- "https://raw.githubusercontent.com/UN-CRAFd/crafd-reference-datasets/refs/heads/main/data/output/"
```

```{r collect-files}
#| include: false
data_path <-  here::here("data", "output")
files <- list.files(data_path, recursive = TRUE, full.names = TRUE)

files_df <- tibble(
    file_name = files |> fs::path_file(),
    file_ext = files |> tools::file_ext(),
    file_rel_path = files  |> fs::path_rel(start = data_path),
    file_github_url = paste0(GITHUB_BASE_URL, file_rel_path),
    file_path = files,
)

# FIXME: add more files extensions as needed
data_ext <-  c("csv", "tsv", "rds", "json") 

files_df <- files_df |> 
  filter(file_ext %in% data_ext) |> 
  arrange(file_name)
```


```{r}
#| results: asis
#| echo: false

library(knitr)          # for knit_child / knit_expand

for (i in seq_len(nrow(files_df))) {

  child_src <- knit_expand(text = c(
    "#### `{{fn}}`",          # H4 heading
    "",
    "```{verbatim}",        # 👈 literal fence you want to *show*
    "{{url}}",
    "```",                  # closing fence
    ""
  ),
  fn  = files_df$file_name[i],
  url = files_df$file_github_url[i])

  # Knit the snippet *as* markdown, then cat the result verbatim
  cat(knit_child(text = child_src, quiet = TRUE), sep = "\n")
}

```